/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as LedgerRouteRouteImport } from './routes/ledger/route'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAssessmentRouteImport } from './routes/_authenticated/assessment'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as LedgerIndexRouteImport } from './routes/ledger/index'
import { Route as LedgerAuthenticatedRouteRouteImport } from './routes/ledger/_authenticated/route'
import { Route as AuthenticatedAdminAssessmentIdRouteImport } from './routes/_authenticated/admin.$assessmentId'
import { Route as AuthenticatedResultsAssessmentIdRouteImport } from './routes/_authenticated/results.$assessmentId'
import { Route as LedgerAuthenticatedDashboardRouteImport } from './routes/ledger/_authenticated/dashboard'
import { Route as LedgerAuthenticatedSettingsRouteImport } from './routes/ledger/_authenticated/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRouteRoute = LedgerRouteRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssessmentRoute = AuthenticatedAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LedgerIndexRoute = LedgerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LedgerRouteRoute,
} as any)
const LedgerAuthenticatedRouteRoute =
  LedgerAuthenticatedRouteRouteImport.update({
    id: '/_authenticated',
    getParentRoute: () => LedgerRouteRoute,
  } as any)
const AuthenticatedAdminAssessmentIdRoute =
  AuthenticatedAdminAssessmentIdRouteImport.update({
    id: '/$assessmentId',
    path: '/$assessmentId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedResultsAssessmentIdRoute =
  AuthenticatedResultsAssessmentIdRouteImport.update({
    id: '/results/$assessmentId',
    path: '/results/$assessmentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LedgerAuthenticatedDashboardRoute =
  LedgerAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LedgerAuthenticatedRouteRoute,
  } as any)
const LedgerAuthenticatedSettingsRoute =
  LedgerAuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LedgerAuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ledger': typeof LedgerRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/assessment': typeof AuthenticatedAssessmentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/ledger/': typeof LedgerIndexRoute
  '/admin/$assessmentId': typeof AuthenticatedAdminAssessmentIdRoute
  '/results/$assessmentId': typeof AuthenticatedResultsAssessmentIdRoute
  '/ledger/dashboard': typeof LedgerAuthenticatedDashboardRoute
  '/ledger/settings': typeof LedgerAuthenticatedSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ledger': typeof LedgerIndexRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/assessment': typeof AuthenticatedAssessmentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/$assessmentId': typeof AuthenticatedAdminAssessmentIdRoute
  '/results/$assessmentId': typeof AuthenticatedResultsAssessmentIdRoute
  '/ledger/dashboard': typeof LedgerAuthenticatedDashboardRoute
  '/ledger/settings': typeof LedgerAuthenticatedSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ledger': typeof LedgerRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ledger/_authenticated': typeof LedgerAuthenticatedRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/assessment': typeof AuthenticatedAssessmentRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/ledger/': typeof LedgerIndexRoute
  '/_authenticated/admin/$assessmentId': typeof AuthenticatedAdminAssessmentIdRoute
  '/_authenticated/results/$assessmentId': typeof AuthenticatedResultsAssessmentIdRoute
  '/ledger/_authenticated/dashboard': typeof LedgerAuthenticatedDashboardRoute
  '/ledger/_authenticated/settings': typeof LedgerAuthenticatedSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ledger'
    | '/auth'
    | '/features'
    | '/pricing'
    | '/reset-password'
    | '/admin'
    | '/assessment'
    | '/dashboard'
    | '/profile'
    | '/ledger/'
    | '/admin/$assessmentId'
    | '/results/$assessmentId'
    | '/ledger/dashboard'
    | '/ledger/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/features'
    | '/pricing'
    | '/reset-password'
    | '/ledger'
    | '/admin'
    | '/assessment'
    | '/dashboard'
    | '/profile'
    | '/admin/$assessmentId'
    | '/results/$assessmentId'
    | '/ledger/dashboard'
    | '/ledger/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ledger'
    | '/auth'
    | '/features'
    | '/pricing'
    | '/reset-password'
    | '/ledger/_authenticated'
    | '/_authenticated/admin'
    | '/_authenticated/assessment'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/ledger/'
    | '/_authenticated/admin/$assessmentId'
    | '/_authenticated/results/$assessmentId'
    | '/ledger/_authenticated/dashboard'
    | '/ledger/_authenticated/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LedgerRouteRoute: typeof LedgerRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FeaturesRoute: typeof FeaturesRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment': {
      id: '/_authenticated/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AuthenticatedAssessmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/ledger/': {
      id: '/ledger/'
      path: '/'
      fullPath: '/ledger/'
      preLoaderRoute: typeof LedgerIndexRouteImport
      parentRoute: typeof LedgerRouteRoute
    }
    '/ledger/_authenticated': {
      id: '/ledger/_authenticated'
      path: ''
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerAuthenticatedRouteRouteImport
      parentRoute: typeof LedgerRouteRoute
    }
    '/_authenticated/admin/$assessmentId': {
      id: '/_authenticated/admin/$assessmentId'
      path: '/$assessmentId'
      fullPath: '/admin/$assessmentId'
      preLoaderRoute: typeof AuthenticatedAdminAssessmentIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/results/$assessmentId': {
      id: '/_authenticated/results/$assessmentId'
      path: '/results/$assessmentId'
      fullPath: '/results/$assessmentId'
      preLoaderRoute: typeof AuthenticatedResultsAssessmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/ledger/_authenticated/dashboard': {
      id: '/ledger/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/ledger/dashboard'
      preLoaderRoute: typeof LedgerAuthenticatedDashboardRouteImport
      parentRoute: typeof LedgerAuthenticatedRouteRoute
    }
    '/ledger/_authenticated/settings': {
      id: '/ledger/_authenticated/settings'
      path: '/settings'
      fullPath: '/ledger/settings'
      preLoaderRoute: typeof LedgerAuthenticatedSettingsRouteImport
      parentRoute: typeof LedgerAuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAssessmentIdRoute: typeof AuthenticatedAdminAssessmentIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAssessmentIdRoute: AuthenticatedAdminAssessmentIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAssessmentRoute: typeof AuthenticatedAssessmentRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedResultsAssessmentIdRoute: typeof AuthenticatedResultsAssessmentIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAssessmentRoute: AuthenticatedAssessmentRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedResultsAssessmentIdRoute: AuthenticatedResultsAssessmentIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LedgerAuthenticatedRouteRouteChildren {
  LedgerAuthenticatedDashboardRoute: typeof LedgerAuthenticatedDashboardRoute
  LedgerAuthenticatedSettingsRoute: typeof LedgerAuthenticatedSettingsRoute
}

const LedgerAuthenticatedRouteRouteChildren: LedgerAuthenticatedRouteRouteChildren =
  {
    LedgerAuthenticatedDashboardRoute: LedgerAuthenticatedDashboardRoute,
    LedgerAuthenticatedSettingsRoute: LedgerAuthenticatedSettingsRoute,
  }

const LedgerAuthenticatedRouteRouteWithChildren =
  LedgerAuthenticatedRouteRoute._addFileChildren(
    LedgerAuthenticatedRouteRouteChildren,
  )

interface LedgerRouteRouteChildren {
  LedgerAuthenticatedRouteRoute: typeof LedgerAuthenticatedRouteRouteWithChildren
  LedgerIndexRoute: typeof LedgerIndexRoute
}

const LedgerRouteRouteChildren: LedgerRouteRouteChildren = {
  LedgerAuthenticatedRouteRoute: LedgerAuthenticatedRouteRouteWithChildren,
  LedgerIndexRoute: LedgerIndexRoute,
}

const LedgerRouteRouteWithChildren = LedgerRouteRoute._addFileChildren(
  LedgerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LedgerRouteRoute: LedgerRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FeaturesRoute: FeaturesRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
