/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAssessmentRouteImport } from './routes/_authenticated/assessment'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminAssessmentIdRouteImport } from './routes/_authenticated/admin.$assessmentId'
import { Route as AuthenticatedResultsAssessmentIdRouteImport } from './routes/_authenticated/results.$assessmentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssessmentRoute = AuthenticatedAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAssessmentIdRoute =
  AuthenticatedAdminAssessmentIdRouteImport.update({
    id: '/$assessmentId',
    path: '/$assessmentId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedResultsAssessmentIdRoute =
  AuthenticatedResultsAssessmentIdRouteImport.update({
    id: '/results/$assessmentId',
    path: '/results/$assessmentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ledger': typeof LedgerRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/assessment': typeof AuthenticatedAssessmentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/$assessmentId': typeof AuthenticatedAdminAssessmentIdRoute
  '/results/$assessmentId': typeof AuthenticatedResultsAssessmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ledger': typeof LedgerRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/assessment': typeof AuthenticatedAssessmentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/$assessmentId': typeof AuthenticatedAdminAssessmentIdRoute
  '/results/$assessmentId': typeof AuthenticatedResultsAssessmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/ledger': typeof LedgerRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/assessment': typeof AuthenticatedAssessmentRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/$assessmentId': typeof AuthenticatedAdminAssessmentIdRoute
  '/_authenticated/results/$assessmentId': typeof AuthenticatedResultsAssessmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ledger'
    | '/reset-password'
    | '/admin'
    | '/assessment'
    | '/dashboard'
    | '/admin/$assessmentId'
    | '/results/$assessmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ledger'
    | '/reset-password'
    | '/admin'
    | '/assessment'
    | '/dashboard'
    | '/admin/$assessmentId'
    | '/results/$assessmentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/ledger'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/assessment'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/$assessmentId'
    | '/_authenticated/results/$assessmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LedgerRoute: typeof LedgerRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment': {
      id: '/_authenticated/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AuthenticatedAssessmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/$assessmentId': {
      id: '/_authenticated/admin/$assessmentId'
      path: '/$assessmentId'
      fullPath: '/admin/$assessmentId'
      preLoaderRoute: typeof AuthenticatedAdminAssessmentIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/results/$assessmentId': {
      id: '/_authenticated/results/$assessmentId'
      path: '/results/$assessmentId'
      fullPath: '/results/$assessmentId'
      preLoaderRoute: typeof AuthenticatedResultsAssessmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAssessmentIdRoute: typeof AuthenticatedAdminAssessmentIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAssessmentIdRoute: AuthenticatedAdminAssessmentIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAssessmentRoute: typeof AuthenticatedAssessmentRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedResultsAssessmentIdRoute: typeof AuthenticatedResultsAssessmentIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAssessmentRoute: AuthenticatedAssessmentRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedResultsAssessmentIdRoute: AuthenticatedResultsAssessmentIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LedgerRoute: LedgerRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
